/* Generated by re2c 0.9.10 on Mon Feb 27 18:07:08 2006 */

/* stscan.re
 * Scott Bronson
 *
 * This file is covered by the MIT license.
 *
 * Scanner for status files files.
 * This file needs to be processed by re2c, http://re2c.org
 */

#include "stscan.h"


/* This scanner scans lines.  When it finds a line that begins
 * with a recognized token, it returns that token with the text
 * of the entire line.  Otherwise, it returns stGARBAGE.
 *
 * Note that this scanner only returns complete lines.  If the file
 * doesn't end with a newline, then the last line will be lost.
 * I think.
 */

int stscan_start(scanstate *ss)
{
    scanner_enter(ss);
    scan_inc_line(ss);



{
	YYCTYPE yych;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 8) YYFILL(8);
	yych = *YYCURSOR;
	switch(yych){
	case 0x0A:	goto yy10;
	case 'A':	goto yy7;
	case 'C':	goto yy3;
	case 'D':	goto yy6;
	case 'P':	goto yy4;
	case 'R':	goto yy5;
	case 'S':	goto yy2;
	default:	goto yy8;
	}
yy2:	yych = *++YYCURSOR;
	switch(yych){
	case 'T':	goto yy77;
	default:	goto yy9;
	}
yy3:	yych = *++YYCURSOR;
	switch(yych){
	case 'O':	goto yy67;
	default:	goto yy9;
	}
yy4:	yych = *++YYCURSOR;
	switch(yych){
	case 'R':	goto yy55;
	default:	goto yy9;
	}
yy5:	yych = *++YYCURSOR;
	switch(yych){
	case 'U':	goto yy44;
	default:	goto yy9;
	}
yy6:	yych = *++YYCURSOR;
	switch(yych){
	case 'I':	goto yy23;
	case 'O':	goto yy24;
	default:	goto yy9;
	}
yy7:	yych = *++YYCURSOR;
	switch(yych){
	case 'B':	goto yy12;
	default:	goto yy9;
	}
yy8:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy9;
yy9:	switch(yych){
	case 0x0A:	goto yy10;
	default:	goto yy8;
	}
yy10:	++YYCURSOR;
	goto yy11;
yy11:

{ return stGARBAGE; }

yy12:	yych = *++YYCURSOR;
	switch(yych){
	case 'O':	goto yy13;
	default:	goto yy9;
	}
yy13:	yych = *++YYCURSOR;
	switch(yych){
	case 'R':	goto yy14;
	default:	goto yy9;
	}
yy14:	yych = *++YYCURSOR;
	switch(yych){
	case 'T':	goto yy15;
	default:	goto yy9;
	}
yy15:	yych = *++YYCURSOR;
	switch(yych){
	case 'E':	goto yy16;
	default:	goto yy9;
	}
yy16:	yych = *++YYCURSOR;
	switch(yych){
	case 'D':	goto yy17;
	default:	goto yy9;
	}
yy17:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy18;
yy18:	switch(yych){
	case 0x09:	case ' ':	goto yy17;
	case 0x0A:	goto yy10;
	case ':':	goto yy19;
	default:	goto yy8;
	}
yy19:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy20;
yy20:	switch(yych){
	case 0x0A:	goto yy21;
	default:	goto yy19;
	}
yy21:	++YYCURSOR;
	goto yy22;
yy22:

{ return stABORTED; }

yy23:	yych = *++YYCURSOR;
	switch(yych){
	case 'S':	goto yy33;
	default:	goto yy9;
	}
yy24:	yych = *++YYCURSOR;
	switch(yych){
	case 'N':	goto yy25;
	default:	goto yy9;
	}
yy25:	yych = *++YYCURSOR;
	switch(yych){
	case 'E':	goto yy26;
	default:	goto yy9;
	}
yy26:	yych = *++YYCURSOR;
	switch(yych){
	case 0x09:	case ' ':	goto yy29;
	case 0x0A:	goto yy27;
	default:	goto yy8;
	}
yy27:	++YYCURSOR;
	goto yy28;
yy28:

{ return stDONE; }

yy29:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy30;
yy30:	switch(yych){
	case 0x09:	case ' ':	goto yy29;
	case 0x0A:	goto yy27;
	default:	goto yy31;
	}
yy31:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy32;
yy32:	switch(yych){
	case 0x0A:	goto yy27;
	default:	goto yy31;
	}
yy33:	yych = *++YYCURSOR;
	switch(yych){
	case 'A':	goto yy34;
	default:	goto yy9;
	}
yy34:	yych = *++YYCURSOR;
	switch(yych){
	case 'B':	goto yy35;
	default:	goto yy9;
	}
yy35:	yych = *++YYCURSOR;
	switch(yych){
	case 'L':	goto yy36;
	default:	goto yy9;
	}
yy36:	yych = *++YYCURSOR;
	switch(yych){
	case 'E':	goto yy37;
	default:	goto yy9;
	}
yy37:	yych = *++YYCURSOR;
	switch(yych){
	case 'D':	goto yy38;
	default:	goto yy9;
	}
yy38:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy39;
yy39:	switch(yych){
	case 0x09:	case ' ':	goto yy38;
	case 0x0A:	goto yy10;
	case ':':	goto yy40;
	default:	goto yy8;
	}
yy40:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy41;
yy41:	switch(yych){
	case 0x0A:	goto yy42;
	default:	goto yy40;
	}
yy42:	++YYCURSOR;
	goto yy43;
yy43:

{ return stDISABLED; }

yy44:	yych = *++YYCURSOR;
	switch(yych){
	case 'N':	goto yy45;
	default:	goto yy9;
	}
yy45:	yych = *++YYCURSOR;
	switch(yych){
	case 'N':	goto yy46;
	default:	goto yy9;
	}
yy46:	yych = *++YYCURSOR;
	switch(yych){
	case 'I':	goto yy47;
	default:	goto yy9;
	}
yy47:	yych = *++YYCURSOR;
	switch(yych){
	case 'N':	goto yy48;
	default:	goto yy9;
	}
yy48:	yych = *++YYCURSOR;
	switch(yych){
	case 'G':	goto yy49;
	default:	goto yy9;
	}
yy49:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy50;
yy50:	switch(yych){
	case 0x09:	case ' ':	goto yy49;
	case 0x0A:	goto yy10;
	case ':':	goto yy51;
	default:	goto yy8;
	}
yy51:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy52;
yy52:	switch(yych){
	case 0x0A:	goto yy53;
	default:	goto yy51;
	}
yy53:	++YYCURSOR;
	goto yy54;
yy54:

{ return stRUNNING; }

yy55:	yych = *++YYCURSOR;
	switch(yych){
	case 'E':	goto yy56;
	default:	goto yy9;
	}
yy56:	yych = *++YYCURSOR;
	switch(yych){
	case 'P':	goto yy57;
	default:	goto yy9;
	}
yy57:	yych = *++YYCURSOR;
	switch(yych){
	case 'A':	goto yy58;
	default:	goto yy9;
	}
yy58:	yych = *++YYCURSOR;
	switch(yych){
	case 'R':	goto yy59;
	default:	goto yy9;
	}
yy59:	yych = *++YYCURSOR;
	switch(yych){
	case 'E':	goto yy60;
	default:	goto yy9;
	}
yy60:	yych = *++YYCURSOR;
	switch(yych){
	case 0x09:	case ' ':	goto yy63;
	case 0x0A:	goto yy61;
	default:	goto yy8;
	}
yy61:	++YYCURSOR;
	goto yy62;
yy62:

{ return stPREPARE; }

yy63:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy64;
yy64:	switch(yych){
	case 0x09:	case ' ':	goto yy63;
	case 0x0A:	goto yy61;
	default:	goto yy65;
	}
yy65:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy66;
yy66:	switch(yych){
	case 0x0A:	goto yy61;
	default:	goto yy65;
	}
yy67:	yych = *++YYCURSOR;
	switch(yych){
	case 'N':	goto yy68;
	default:	goto yy9;
	}
yy68:	yych = *++YYCURSOR;
	switch(yych){
	case 'F':	goto yy69;
	default:	goto yy9;
	}
yy69:	yych = *++YYCURSOR;
	switch(yych){
	case 'I':	goto yy70;
	default:	goto yy9;
	}
yy70:	yych = *++YYCURSOR;
	switch(yych){
	case 'G':	goto yy71;
	default:	goto yy9;
	}
yy71:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy72;
yy72:	switch(yych){
	case 0x09:	case ' ':	goto yy71;
	case 0x0A:	goto yy10;
	case ':':	goto yy73;
	default:	goto yy8;
	}
yy73:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy74;
yy74:	switch(yych){
	case 0x0A:	goto yy75;
	default:	goto yy73;
	}
yy75:	++YYCURSOR;
	goto yy76;
yy76:

{ return stCONFIG; }

yy77:	yych = *++YYCURSOR;
	switch(yych){
	case 'A':	goto yy78;
	default:	goto yy9;
	}
yy78:	yych = *++YYCURSOR;
	switch(yych){
	case 'R':	goto yy79;
	default:	goto yy9;
	}
yy79:	yych = *++YYCURSOR;
	switch(yych){
	case 'T':	goto yy80;
	default:	goto yy9;
	}
yy80:	yych = *++YYCURSOR;
	switch(yych){
	case 0x09:	case ' ':	goto yy83;
	case 0x0A:	goto yy81;
	default:	goto yy8;
	}
yy81:	++YYCURSOR;
	goto yy82;
yy82:

{ return stSTART; }

yy83:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy84;
yy84:	switch(yych){
	case 0x09:	case ' ':	goto yy83;
	case 0x0A:	goto yy81;
	default:	goto yy85;
	}
yy85:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy86;
yy86:	switch(yych){
	case 0x0A:	goto yy81;
	default:	goto yy85;
	}
}


}


/** Prepares the given scanner to scan a status file.
 *
 *  @param ss the scanstate to attach to.  Passing NULL is safely ignored.
 *  @returns ss.  Always.  This routine makes no calls that can fail.
 */

scanstate* stscan_attach(scanstate *ss)
{
    if(ss) {
        ss->state = stscan_start;
    }

    return ss;
}

